name: Auto Merge PRs from dependabot

on:
    pull_request_target:
        types: [opened, synchronize]

jobs:
    autoapprove-for-bot:
        name: Autoaprove PRs fom dependabot
        runs-on: ubuntu-latest
        if: >
            contains(fromJson('"dependabot[bot]", "dependabot-preview[bot]"]'), github.event.pull_request.user.login) &&
            contains(fromJson('"dependabot[bot]", "dependabot-preview[bot]"]'), github.actor)
        steps:
            - name: Autoaprove
              uses: hmarr/auto-approve-action@v4
              with:
                  review-message: 'Auto approved automated PR'
                  github-token: ${{ secrets.GH_TOKEN_BOT_PR }}
            - name: Label automerge
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      github.rest.issues.addLabels({
                      issue_number: context.issue.number,
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      labels: ['automerge']
                      })
