name: Auto Merge PRs from dependabot

on:
    pull_request_target:
        types: [opened, synchronize]

jobs:
    autoapprove-for-bot:
        name: Autoaprove PRs fom dependabot
        runs-on: ubuntu-latest
        if: >
            github.event.pull_request.user.login == 'dependabot[bot]' || 
            github.event.pull_request.user.login == 'dependabot-preview[bot]' && 
            (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')
        steps:
            - name: Decode the GitHub App Private Key
              id: decode
              run: |
                  private_key=$(echo "${{ secrets.GH_APP_PRIVATE_KEY }}" | base64 -d | awk 'BEGIN {ORS="\\n"} {print}' | head -c -2) &> /dev/null
                  echo "::add-mask::$private_key"
                  echo "private-key=$private_key" >> "$GITHUB_OUTPUT"
            - uses: actions/create-github-app-token@v1
              id: app-token
              with:
                  # required
                  app-id: ${{ secrets.GH_APP_ID }}
                  private-key: ${{ steps.decode.outputs.private-key }}
            - name: Harden Runner
              uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
              with:
                  egress-policy: audit

            - name: Autoaprove
              uses: hmarr/auto-approve-action@8f929096a962e83ccdfa8afcf855f39f12d4dac7 # v4
              with:
                  review-message: 'Auto approved automated PR'
                  github-token: ${{ steps.app-token.outputs.token }}
            - name: Label automerge
              uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
              with:
                  github-token: ${{ steps.app-token.outputs.token }}
                  script: |
                      github.rest.issues.addLabels({
                      issue_number: context.issue.number,
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      labels: ['automerge']
                      })
