name: Auto Merge PRs from dependabot

on:
    pull_request_target:
        types: [opened, synchronize]

jobs:
    autoapprove-for-bot:
        name: Autoaprove PRs fom dependabot
        runs-on: ubuntu-latest
        if: >
            contains(fromJson('"dependabot[bot]", "dependabot-preview[bot]"]'), github.event.pull_request.user.login) &&
            contains(fromJson('"dependabot[bot]", "dependabot-preview[bot]"]'), github.actor)
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
              with:
                egress-policy: audit

            - name: Autoaprove
              uses: hmarr/auto-approve-action@8f929096a962e83ccdfa8afcf855f39f12d4dac7 # v4
              with:
                  review-message: 'Auto approved automated PR'
                  github-token: ${{ secrets.GH_TOKEN_BOT_PR }}
            - name: Label automerge
              uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      github.rest.issues.addLabels({
                      issue_number: context.issue.number,
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      labels: ['automerge']
                      })
