name: Deployment

# Deploy bi-weekly At 05:00 on Monday and Thursday.
on:
    schedule:
        - cron: '0 5 * * 1,4'

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build_docs:
        if: github.repository == 'jerensl/www.jerenslensun.com'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
            - name: Deploy Storybook Docs
              uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
              with:
                  install_command: pnpm install # default: npm ci
                  build_command: pnpm run build:storybook # default: npm run build-storybook
                  path: storybook-static # default: dist/storybook
                  checkout: false # default: true
    azure_deploy:
        if: github.repository == 'jerensl/www.jerenslensun.com'
        uses: ./.github/workflows/azure.yml
        secrets: inherit
    lhci:
        if: github.repository == 'jerensl/www.jerenslensun.com'
        needs: azure_deploy
        uses: ./.github/workflows/lighthouse.yml
        secrets: inherit
        with:
            static_web_url: ${{ needs.azure_deploy.outputs.static_web_app_url }}
