name: Deployment

# Deploy bi-weekly At 05:00 on Monday and Thursday.
on:
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
    schedule:
        - cron: '0 5 * * 1,4'

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build_docs:
        if: github.repository == 'jerensl/www.jerenslensun.com'
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
              with:
                  egress-policy: audit

            - name: Checkout
              uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
            - name: Install pnpm
              uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
              with:
                  version: 9
            - name: Setup Node
              uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
              with:
                  node-version: '18.x'
            - name: Deploy Storybook Docs
              uses: bitovi/github-actions-storybook-to-github-pages@b75ece8f984a32b2adb322065d7a8a2cc8db2d52 # v1.0.3
              with:
                  install_command: pnpm install # default: npm ci
                  build_command: pnpm run build:storybook # default: npm run build-storybook
                  path: storybook-static # default: dist/storybook
                  checkout: false # default: true
    azure_deploy:
        if: github.repository == 'jerensl/www.jerenslensun.com'
        uses: ./.github/workflows/azure.yml
        secrets: inherit
    lhci:
        if: github.repository == 'jerensl/www.jerenslensun.com'
        needs: azure_deploy
        uses: ./.github/workflows/lighthouse.yml
        secrets: inherit
        with:
            static_web_url: ${{ needs.azure_deploy.outputs.static_web_app_url }}
