name: Build and Test

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize]

jobs:
    lint:
        if: github.repository == 'jerensl/www.jerenslensun.com'
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup Node.js 18.x
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
                  cache: 'yarn'
            - name: Install locked dependencies
              run: yarn install --frozen-lockfile --prefer-offline
            - name: Lint files
              run: yarn lint
              env:
                  CI: true
    type-check:
        if: github.repository == 'jerensl/www.jerenslensun.com'
        name: Type check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup Node.js 18.x
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
                  cache: 'yarn'
            - name: Install locked dependencies
              run: yarn install --frozen-lockfile --prefer-offline
            - name: Perform type checking
              run: yarn type-check
              env:
                  CI: true
    test:
        if: github.repository == 'jerensl/www.jerenslensun.com'
        name: Unit and integration tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup Node.js 18.x
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
                  cache: 'yarn'
            - name: Install locked dependencies
              run: yarn install --frozen-lockfile --prefer-offline
            - name: Check Code Coverage
              run: yarn test:coverage
            - name: Upload code coverage reports to Codecov
              uses: codecov/codecov-action@v2
    e2e:
        if: github.repository == 'jerensl/www.jerenslensun.com'
        name: End-to-end tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup Node.js 18.x
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
                  cache: 'yarn'
            - name: Install Cypress
              run: yarn add cypress
            - name: Build the web app
              run: yarn build
            - name: Run Cypress
              uses: cypress-io/github-action@v4
              with:
                  record: true
                  start: yarn start
                  wait-on: 'http://localhost:3000'
              env:
                  CI: true
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
