name: Build and Test

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize]

jobs:
    install-deps:
        if: github.repository == 'jerensl/www.jerensl.com'
        name: Install dependencies
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup Node.js 18.x
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
                  cache: 'yarn'
            - name: Install locked dependencies
              run: yarn install --frozen-lockfile --prefer-offline

    lint:
        if: github.repository == 'jerensl/www.jerensl.com'
        name: ESLint
        runs-on: ubuntu-latest
        needs: install-deps
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Lint files
              run: yarn run lint
              env:
                  CI: true
    type-check:
        if: github.repository == 'jerensl/www.jerensl.com'
        name: Type check
        runs-on: ubuntu-latest
        needs: install-deps
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Perform type checking
              run: yarn run type-check
              env:
                  CI: true
    test:
        name: Unit and integration tests
        runs-on: ubuntu-latest
        needs: install-deps
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Check Code Coverage
              run: yarn run test:coverage
            - name: Upload code coverage reports to Codecov
              uses: codecov/codecov-action@v2
    e2e:
        name: End-to-end tests
        runs-on: ubuntu-latest
        needs: install-deps
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Install Cypress
              run: yarn add cypress
            - name: Build dependencies
              run: yarn build
            - name: Run Cypress
              uses: cypress-io/github-action@v4
              with:
                  record: true
                  start: yarn start
                  wait-on: 'http://localhost:3000'
              env:
                  CI: true
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  needs: install-deps
