name: CI

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize]

    workflow_dispatch:

jobs:
    deps:
        name: Install dependencies
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

            - name: Install locked dependencies
              run: yarn install --frozen-lockfile

            - name: Fetch the latest data
              run: yarn run mirror-box

            - name: Cache dependencies
              uses: actions/cache@v1
              id: cache-deps
              with:
                  path: '.'
                  key: ${{ github.sha }}

    test:
        runs-on: ubuntu-latest
        needs: install-deps
        steps:
            - name: Restore cached dependencies
              uses: actions/cache@v1
              id: restore-deps
              with:
                  path: '.'
                  key: ${{ github.sha }}

            - name: Setup Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

            - name: Check Code Coverage
              run: yarn test:coverage

            - name: Upload code coverage reports to Codecov
              uses: codecov/codecov-action@v2
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
