name: CI

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize]

jobs:
    install-deps:
        name: Install dependencies
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

						- name: Cache Package
						  uses: actions/cache@v2
							with:
								path: '**/node_modules'
								key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install locked dependencies
              run: yarn install --frozen-lockfile

            - name: Fetch the latest data
              run: yarn run mirror-box

    test:
        name: Unit and integration tests
        runs-on: ubuntu-latest
        needs: install-deps
        steps:
            - name: Restore cached dependencies
						  uses: actions/cache@v2
							with:
								path: '**/node_modules'
								key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Setup Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

            - name: Check Code Coverage
              run: yarn test:coverage

            - name: Upload code coverage reports to Codecov
              uses: codecov/codecov-action@v2
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
