name: Staging on PR

on:
    workflow_run:
        workflows: ['Build, lint and Test']
        types: [completed]

permissions:
    issues: write
    contents: read
    pull-requests: write

jobs:
    build_and_deploy_to_azure:
        if: github.repository == 'jerensl/www.jerenslensun.com' && (github.event_name == 'pull_request' && github.event.action != 'closed')
        runs-on: ubuntu-latest
        name: Build and Deploy Job
        outputs:
            static_web_app_url: ${{ steps.swa.outputs.static_web_app_url }}
        steps:
            - name: Dump GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
            - uses: actions/checkout@v4
              with:
                  submodules: true
            - name: Build And Deploy
              id: swa
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
                  production_branch: 'main'
                  action: 'upload'
                  ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
                  # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
                  app_location: '/' # App source code path
                  api_location: '' # Api source code path - optional
                  output_location: 'out' # Built app content directory - optional
                  ###### End of Repository/Build Configurations ######
              env:
                  IS_STATIC_EXPORT: true
                  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
                  NEXT_PUBLIC_FCM_VAPID_KEY: ${{ secrets.NEXT_PUBLIC_FCM_VAPID_KEY }}
                  NEXT_PUBLIC_IMAGES_CDN: ${{ secrets.NEXT_PUBLIC_IMAGES_CDN }}
    close_pull_request_job:
        if: github.repository == 'jerensl/www.jerenslensun.com' && (github.event_name == 'pull_request' && github.event.action == 'closed')
        runs-on: ubuntu-latest
        name: Close Pull Request Job
        steps:
            - name: Close Pull Request
              id: closepullrequest
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
                  action: 'close'
